services:
  dogecoincore_app:
    image: dogecoincore
    build: ./Docker
    restart: unless-stopped
    volumes:
      - ./app/conf:/config:rw
    networks:
      PRIVATE:
        ipv4_address: 10.13.16.56
    env_file:
      - stack.env
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"
      interval: 10s
      timeout: 10s
      retries: 20

networks:
  PRIVATE:
    external: true
