services:
  dogecoincore_app:
    image: dogecoincore
    container_name: dogecoincore_app
    hostname: dogecoincore_app
    restart: unless-stopped
    stop_grace_period: 30s
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/dogecoincore_stack/app/conf:/config:rw
    networks:
      PRIVATE:
        ipv4_address: 10.13.16.56
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"
      interval: 10s
      timeout: 10s
      retries: 20

networks:
  PRIVATE:
    external: true
